project:
  type: website
  output-dir: docs
  pre-render:  # This can be deleted if you are using the manually curated list of publications in publications.qmd
    - scripts/fetch-orcid.ts  # Automatically generate publications.yml from ORCID publications
    #- scripts/fetch-cv.ts

# Meta
description-meta: "Quarto Academic Website Template adapted from a template by Dr. Gang He"
author-meta: "Dr. Gang He"

website:
  title: "Gabriel Frazer-McKee"
  description: "Academic website of Gabriel Frazer-McKee"
  site-url: "https://www.gabriel-frazer-mckee.com"
 
  navbar:
    background: light
    title: "GABRIEL FRAZER-MCKEE"

    right:
      - text: About
        href: about.qmd
      - text: Research
        href: projects.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog
        href: posts.qmd
      - text: Publications
        href: publications.qmd
      - text: CV
        href: files/cv.pdf
  
  page-navigation: true
  
  page-footer: 
    left: ""
    center: "© 2022 –<script>document.write(new Date().getFullYear())</script> Gabriel Frazer-McKee · Made with [Quarto](https://quarto.org)"
    right:  
      - text: Contact
        href: contact.qmd
      - icon: rss
        href: posts.xml
        target: _blank
        
  search:
    location: navbar
    type: overlay
  
  reader-mode: false

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
    
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles-dark.scss]
    toc: false
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: none
    include-in-header: "files/includes/_academic.qmd"

